# Generated by Django 5.1.7 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matematicas_o_historia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lengua_y_litertura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idioma', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prueba_especifica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nota_media', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
