# Generated by Django 5.1.7 on 2025-03-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_anotacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anotacion',
        ),
    ]
